// ============================================
// UTMS - Mock Data for Development
// ============================================

import { v4 as uuidv4 } from 'uuid';
import type {
  Application,
  User,
  UserRoleAssignment,
  TestRequest,
  Requirement,
  Flow,
  TestCase,
  TestRun,
  Bug,
  RetestTask,
  RunIssue,
  Checklist,
  PlaywrightRun,
  ReleasePublish,
  AuditLog,
  Comment,
  Notification,
  Attachment,
} from '../types';

// Applications
export const mockApplications: Application[] = [
  {
    id: 'app-1',
    name: 'سامانه بانکداری آنلاین',
    code: 'ONLINE_BANKING',
    description: 'سیستم بانکداری اینترنتی برای مشتریان',
    cdeFrontUrl: 'https://cde.edus.ir/front/directory/medu-community%3EApp',
    cdeDataServiceUrl: 'https://cde.edus.ir/dservice/directory/medu-community%3EApp',
    cdeGatewayUrl: 'https://cde.edus.ir/back/medu-ai/medu-community%3E?return=/workspace/medu-ai',
    workflowPolicyId: 'standard-tech-lead',
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'app-2',
    name: 'سامانه مدیریت منابع انسانی',
    code: 'HRM',
    description: 'سیستم مدیریت کارکنان و منابع انسانی',
    cdeFrontUrl: 'https://cde.edus.ir/front/directory/hrm%3EApp',
    cdeDataServiceUrl: 'https://cde.edus.ir/dservice/directory/hrm%3EApp',
    cdeGatewayUrl: 'https://cde.edus.ir/back/hrm/hrm%3E?return=/workspace/hrm',
    workflowPolicyId: 'qa-owned-release',
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'app-3',
    name: 'پورتال کارمندان',
    code: 'EMPLOYEE_PORTAL',
    description: 'پورتال خدمات کارمندان',
    cdeFrontUrl: 'https://cde.edus.ir/front/directory/employee-portal%3EApp',
    cdeDataServiceUrl: 'https://cde.edus.ir/dservice/directory/employee-portal%3EApp',
    cdeGatewayUrl: 'https://cde.edus.ir/back/employee-portal/employee-portal%3E?return=/workspace/employee-portal',
    workflowPolicyId: 'standard-tech-lead',
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

// Users
// Users 1-8: assigned at SYSTEMS level (specific apps)
// Users 10-15: assigned at APP level (see ALL systems)
// user-admin: SYSTEM_ADMIN at APP level
export const mockUsers: User[] = [
  // System-level users (specific app assignments)
  { id: 'user-1', nationalCode: '0012345678', phoneNumber: '09121234567', fullName: 'احمد محمدی', email: 'ahmad@example.com', isActive: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: 'user-2', nationalCode: '0023456789', phoneNumber: '09122345678', fullName: 'سارا احمدی', email: 'sara@example.com', isActive: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: 'user-3', nationalCode: '0034567890', phoneNumber: '09123456789', fullName: 'علی رضایی', email: 'ali@example.com', isActive: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: 'user-4', nationalCode: '0045678901', phoneNumber: '09124567890', fullName: 'مریم کریمی', email: 'maryam@example.com', isActive: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: 'user-5', nationalCode: '0056789012', phoneNumber: '09125678901', fullName: 'حسین نوری', email: 'hossein@example.com', isActive: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: 'user-6', nationalCode: '0067890123', phoneNumber: '09126789012', fullName: 'زهرا فتحی', email: 'zahra@example.com', isActive: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: 'user-7', nationalCode: '0078901234', phoneNumber: '09127890123', fullName: 'محمد حسینی', email: 'mohammad@example.com', isActive: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: 'user-8', nationalCode: '0089012345', phoneNumber: '09128901234', fullName: 'فاطمه صادقی', email: 'fatemeh@example.com', isActive: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  // App-level users (see ALL systems across the entire app)
  { id: 'user-10', nationalCode: '1012345678', phoneNumber: '09131234567', fullName: 'رضا قاسمی (QA Lead کل)', email: 'reza.qa@example.com', isActive: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: 'user-11', nationalCode: '1023456789', phoneNumber: '09132345678', fullName: 'نسرین طاهری (Tech Lead کل)', email: 'nasrin.tl@example.com', isActive: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: 'user-12', nationalCode: '1034567890', phoneNumber: '09133456789', fullName: 'امیر جعفری (Product Owner کل)', email: 'amir.po@example.com', isActive: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: 'user-13', nationalCode: '1045678901', phoneNumber: '09134567890', fullName: 'لیلا موسوی (QA Specialist کل)', email: 'leila.qs@example.com', isActive: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: 'user-14', nationalCode: '1056789012', phoneNumber: '09135678901', fullName: 'کامران نیکو (BA کل)', email: 'kamran.ba@example.com', isActive: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  { id: 'user-15', nationalCode: '1067890123', phoneNumber: '09136789012', fullName: 'شیما رحیمی (Developer کل)', email: 'shima.dev@example.com', isActive: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
  // System Admin
  { id: 'user-admin', nationalCode: '0010000000', phoneNumber: '09120000000', fullName: 'مدیر سیستم', email: 'admin@example.com', isActive: true, createdAt: '2024-01-01T00:00:00Z', updatedAt: '2024-01-01T00:00:00Z' },
];

// User Role Assignments
// scope: 'APP' = access to ALL systems in the app, 'SYSTEMS' = one or more specific systems
// APP-level users see data from ALL applications in their cartables
// SYSTEMS-level users see data ONLY from their assigned application(s)
export const mockUserRoleAssignments: UserRoleAssignment[] = [
  // ===== SYSTEMS-level users (see only their selected app set) =====
  { id: 'ura-1', userId: 'user-1', applicationId: 'app-1', applicationIds: ['app-1'], role: 'DEVELOPER', scope: 'SYSTEMS', isActive: true },
  { id: 'ura-2', userId: 'user-2', applicationId: 'app-1', applicationIds: ['app-1'], role: 'QA_LEAD', scope: 'SYSTEMS', isActive: true },
  { id: 'ura-3', userId: 'user-3', applicationId: 'app-1', applicationIds: ['app-1'], role: 'QA_SPECIALIST', scope: 'SYSTEMS', isActive: true },
  { id: 'ura-4', userId: 'user-4', applicationId: 'app-1', applicationIds: ['app-1'], role: 'BA', scope: 'SYSTEMS', isActive: true },
  { id: 'ura-5', userId: 'user-5', applicationId: 'app-1', applicationIds: ['app-1', 'app-2', 'app-3'], role: 'SECURITY_REVIEWER', scope: 'APP', isActive: true },
  { id: 'ura-6', userId: 'user-6', applicationId: 'app-1', applicationIds: ['app-1'], role: 'TECH_LEAD', scope: 'SYSTEMS', isActive: true },
  { id: 'ura-7', userId: 'user-7', applicationId: 'app-1', applicationIds: ['app-1'], role: 'PRODUCT_OWNER', scope: 'SYSTEMS', isActive: true },
  { id: 'ura-8', userId: 'user-8', applicationId: 'app-1', applicationIds: ['app-1'], role: 'DEVELOPER', scope: 'SYSTEMS', isActive: true },
  // Cross-app system-level
  { id: 'ura-9', userId: 'user-2', applicationId: 'app-2', applicationIds: ['app-1', 'app-2'], role: 'QA_LEAD', scope: 'SYSTEMS', isActive: true },
  { id: 'ura-10', userId: 'user-1', applicationId: 'app-2', applicationIds: ['app-2'], role: 'DEVELOPER', scope: 'SYSTEMS', isActive: true },
  // A genuine second role for the same user exercises in-session role switching.
  // The two DEVELOPER assignments above are still grouped into one role context.
  { id: 'ura-11', userId: 'user-1', applicationId: 'app-2', applicationIds: ['app-2'], role: 'BA', scope: 'SYSTEMS', isActive: true },

  // ===== APP-level users (see ALL systems across entire app) =====
  // These users see data from app-1, app-2, app-3 — everything
  { id: 'ura-app-qa', userId: 'user-10', applicationId: 'app-1', applicationIds: ['app-1', 'app-2', 'app-3'], role: 'QA_LEAD', scope: 'APP', isActive: true },
  { id: 'ura-app-tl', userId: 'user-11', applicationId: 'app-1', applicationIds: ['app-1', 'app-2', 'app-3'], role: 'TECH_LEAD', scope: 'APP', isActive: true },
  { id: 'ura-app-po', userId: 'user-12', applicationId: 'app-1', applicationIds: ['app-1', 'app-2', 'app-3'], role: 'PRODUCT_OWNER', scope: 'APP', isActive: true },
  { id: 'ura-app-qs', userId: 'user-13', applicationId: 'app-1', applicationIds: ['app-1', 'app-2', 'app-3'], role: 'QA_SPECIALIST', scope: 'APP', isActive: true },
  { id: 'ura-app-ba', userId: 'user-14', applicationId: 'app-1', applicationIds: ['app-1', 'app-2', 'app-3'], role: 'BA', scope: 'APP', isActive: true },
  { id: 'ura-app-dev', userId: 'user-15', applicationId: 'app-1', applicationIds: ['app-1', 'app-2', 'app-3'], role: 'DEVELOPER', scope: 'APP', isActive: true },

  // ===== SYSTEM_ADMIN always at APP level =====
  { id: 'ura-admin', userId: 'user-admin', applicationId: 'app-1', applicationIds: ['app-1', 'app-2', 'app-3'], role: 'SYSTEM_ADMIN', scope: 'APP', isActive: true },
];

// Get user by ID helper
export const getUserById = (id: string): User | undefined => mockUsers.find(u => u.id === id);
export const getApplicationById = (id: string): Application | undefined => mockApplications.find(a => a.id === id);

// Test Requests
export const mockTestRequests: TestRequest[] = [
  {
    id: 'tr-1',
    applicationId: 'app-1',
    title: 'تست ویژگی انتقال وجه جدید',
    description: 'درخواست تست برای قابلیت انتقال وجه بین حساب‌ها با امکان زمان‌بندی',
    version: '2.5.0',
    buildNumber: '1234',
    environment: 'staging',
    priority: 'HIGH',
    riskLevel: 'HIGH',
    status: 'SUBMITTED',
    requesterId: 'user-1',
    requester: getUserById('user-1'),
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-03-01T10:00:00Z',
    submittedAt: '2024-03-01T10:30:00Z',
  },
  {
    id: 'tr-2',
    applicationId: 'app-1',
    title: 'تست ماژول گزارش‌گیری مالی',
    description: 'بررسی عملکرد گزارش‌های مالی جدید شامل گزارش تراکنش‌ها و مانده حساب',
    version: '2.5.0',
    buildNumber: '1235',
    environment: 'staging',
    priority: 'MEDIUM',
    riskLevel: 'MEDIUM',
    status: 'IN_PROGRESS',
    requesterId: 'user-1',
    requester: getUserById('user-1'),
    assigneeId: 'user-3',
    assignee: getUserById('user-3'),
    createdAt: '2024-03-02T09:00:00Z',
    updatedAt: '2024-03-03T14:00:00Z',
    submittedAt: '2024-03-02T09:30:00Z',
    reviewedAt: '2024-03-02T11:00:00Z',
    reviewedById: 'user-2',
  },
  {
    id: 'tr-3',
    applicationId: 'app-1',
    title: 'تست امنیتی ورود دو مرحله‌ای',
    description: 'تست کامل احراز هویت دو مرحله‌ای شامل SMS و Authenticator',
    version: '2.4.5',
    buildNumber: '1200',
    environment: 'staging',
    priority: 'CRITICAL',
    riskLevel: 'CRITICAL',
    status: 'ACCEPTED',
    requesterId: 'user-8',
    requester: getUserById('user-8'),
    assigneeId: 'user-3',
    assignee: getUserById('user-3'),
    createdAt: '2024-02-28T08:00:00Z',
    updatedAt: '2024-03-01T09:00:00Z',
    submittedAt: '2024-02-28T08:30:00Z',
    reviewedAt: '2024-02-28T10:00:00Z',
    reviewedById: 'user-2',
    reviewNotes: 'اولویت بالا - نیاز به تست امنیتی کامل',
  },
  {
    id: 'tr-4',
    applicationId: 'app-1',
    title: 'تست رابط کاربری داشبورد',
    description: 'بررسی تغییرات UI در داشبورد کاربر',
    version: '2.5.1',
    buildNumber: '1240',
    environment: 'development',
    priority: 'LOW',
    riskLevel: 'LOW',
    status: 'DRAFT',
    requesterId: 'user-1',
    requester: getUserById('user-1'),
    createdAt: '2024-03-05T14:00:00Z',
    updatedAt: '2024-03-05T14:00:00Z',
  },
  {
    id: 'tr-5',
    applicationId: 'app-1',
    title: 'تست یکپارچگی با درگاه پرداخت',
    description: 'تست اتصال به درگاه پرداخت جدید و بررسی تراکنش‌های آزمایشی',
    version: '2.5.0',
    buildNumber: '1236',
    environment: 'staging',
    priority: 'HIGH',
    riskLevel: 'HIGH',
    status: 'COMPLETED',
    requesterId: 'user-8',
    requester: getUserById('user-8'),
    assigneeId: 'user-3',
    assignee: getUserById('user-3'),
    createdAt: '2024-02-20T10:00:00Z',
    updatedAt: '2024-03-01T16:00:00Z',
    submittedAt: '2024-02-20T10:30:00Z',
    reviewedAt: '2024-02-20T14:00:00Z',
    reviewedById: 'user-2',
  },
];

// Requirements
export const mockRequirements: Requirement[] = [
  {
    id: 'req-1',
    applicationId: 'app-1',
    title: 'انتقال وجه زمان‌بندی شده',
    description: 'کاربر باید بتواند انتقال وجه را با تاریخ و ساعت مشخص زمان‌بندی کند',
    acceptanceCriteria: '۱. امکان انتخاب تاریخ آینده\n۲. امکان انتخاب ساعت\n۳. نمایش لیست انتقال‌های زمان‌بندی شده\n۴. امکان لغو انتقال زمان‌بندی شده',
    riskNotes: 'ریسک تراکنش‌های مالی - نیاز به تست دقیق',
    status: 'APPROVED',
    createdById: 'user-4',
    createdBy: getUserById('user-4'),
    testRequestId: 'tr-1',
    createdAt: '2024-03-01T11:00:00Z',
    updatedAt: '2024-03-02T09:00:00Z',
  },
  {
    id: 'req-2',
    applicationId: 'app-1',
    title: 'گزارش تراکنش‌های مالی',
    description: 'کاربر باید بتواند گزارش تراکنش‌های خود را با فیلترهای مختلف مشاهده کند',
    acceptanceCriteria: '۱. فیلتر بر اساس تاریخ\n۲. فیلتر بر اساس نوع تراکنش\n۳. فیلتر بر اساس مبلغ\n۴. امکان دانلود گزارش',
    status: 'COMPLETED',
    createdById: 'user-4',
    createdBy: getUserById('user-4'),
    testRequestId: 'tr-2',
    createdAt: '2024-03-02T10:00:00Z',
    updatedAt: '2024-03-02T12:00:00Z',
  },
  {
    id: 'req-3',
    applicationId: 'app-1',
    title: 'احراز هویت دو مرحله‌ای',
    description: 'سیستم باید از احراز هویت دو مرحله‌ای پشتیبانی کند',
    acceptanceCriteria: '۱. پشتیبانی از SMS OTP\n۲. پشتیبانی از Authenticator App\n۳. امکان فعال/غیرفعال‌سازی',
    riskNotes: 'ریسک امنیتی بالا',
    status: 'APPROVED',
    createdById: 'user-4',
    createdBy: getUserById('user-4'),
    testRequestId: 'tr-3',
    createdAt: '2024-02-28T09:00:00Z',
    updatedAt: '2024-02-28T11:00:00Z',
  },
];

// Flows
export const mockFlows: Flow[] = [
  {
    id: 'flow-1',
    requirementId: 'req-1',
    title: 'فلوی ثبت انتقال زمان‌بندی شده',
    description: 'مراحل ثبت یک انتقال وجه زمان‌بندی شده',
    steps: '۱. ورود به منوی انتقال وجه\n۲. انتخاب گزینه زمان‌بندی\n۳. وارد کردن اطلاعات انتقال\n۴. انتخاب تاریخ و ساعت\n۵. تایید و ثبت',
    createdById: 'user-4',
    createdBy: getUserById('user-4'),
    createdAt: '2024-03-01T12:00:00Z',
    updatedAt: '2024-03-01T12:00:00Z',
  },
  {
    id: 'flow-2',
    requirementId: 'req-1',
    title: 'فلوی لغو انتقال زمان‌بندی شده',
    description: 'مراحل لغو یک انتقال وجه زمان‌بندی شده',
    steps: '۱. ورود به لیست انتقال‌های زمان‌بندی شده\n۲. انتخاب انتقال مورد نظر\n۳. کلیک روی دکمه لغو\n۴. تایید لغو',
    createdById: 'user-4',
    createdBy: getUserById('user-4'),
    createdAt: '2024-03-01T12:30:00Z',
    updatedAt: '2024-03-01T12:30:00Z',
  },
  {
    id: 'flow-3',
    requirementId: 'req-2',
    title: 'فیلتر گزارش تراکنش‌ها بر اساس تاریخ',
    description: 'مراحل مشاهده گزارش مالی با فیلتر بازه زمانی',
    steps: '1. ورود به منوی گزارش‌ها\n2. انتخاب گزارش تراکنش‌ها\n3. انتخاب بازه تاریخ\n4. مشاهده نتایج',
    createdById: 'user-4',
    createdBy: getUserById('user-4'),
    createdAt: '2024-03-02T12:30:00Z',
    updatedAt: '2024-03-02T12:30:00Z',
  },
];

// Test Cases
export const mockTestCases: TestCase[] = [
  {
    id: 'tc-1',
    applicationId: 'app-1',
    testRequestId: 'tr-1',
    requirementId: 'req-1',
    flowId: 'flow-1',
    title: 'تست ثبت موفق انتقال زمان‌بندی شده',
    scenario: 'کاربر با موفقیت یک انتقال زمان‌بندی شده ثبت می‌کند',
    preconditions: 'کاربر لاگین کرده باشد\nموجودی کافی داشته باشد',
    testData: 'مبلغ: ۱۰۰۰۰۰۰ ریال\nشماره مقصد: ۱۲۳۴۵۶۷۸۹۰\nتاریخ: فردا ساعت ۱۰:۰۰',
    steps: '۱. ورود به منوی انتقال وجه\n۲. انتخاب انتقال زمان‌بندی شده\n۳. وارد کردن مبلغ\n۴. وارد کردن شماره مقصد\n۵. انتخاب تاریخ و ساعت\n۶. تایید',
    expectedResult: 'پیام موفقیت نمایش داده شود و انتقال در لیست زمان‌بندی‌ها ظاهر شود',
    testType: 'FUNCTIONAL',
    testDesignTechnique: 'SCENARIO',
    priority: 'HIGH',
    riskLevel: 'HIGH',
    qualityAttribute: 'FUNCTIONALITY',
    automationCandidate: true,
    regressionCandidate: true,
    isActive: true,
    isComplete: true,
    status: 'READY',
    createdById: 'user-3',
    createdBy: getUserById('user-3'),
    createdAt: '2024-03-02T10:00:00Z',
    updatedAt: '2024-03-02T10:00:00Z',
  },
  {
    id: 'tc-2',
    applicationId: 'app-1',
    testRequestId: 'tr-1',
    requirementId: 'req-1',
    flowId: 'flow-1',
    title: 'تست انتقال با موجودی ناکافی',
    scenario: 'کاربر سعی می‌کند مبلغی بیش از موجودی انتقال دهد',
    preconditions: 'کاربر لاگین کرده باشد\nموجودی کمتر از مبلغ انتقال باشد',
    testData: 'موجودی: ۵۰۰۰۰۰ ریال\nمبلغ انتقال: ۱۰۰۰۰۰۰ ریال',
    steps: '۱. ورود به منوی انتقال وجه\n۲. وارد کردن مبلغ بیش از موجودی\n۳. تلاش برای تایید',
    expectedResult: 'پیام خطای موجودی ناکافی نمایش داده شود',
    testType: 'FUNCTIONAL',
    testDesignTechnique: 'BOUNDARY_VALUE',
    priority: 'HIGH',
    riskLevel: 'MEDIUM',
    qualityAttribute: 'FUNCTIONALITY',
    automationCandidate: true,
    regressionCandidate: true,
    isActive: true,
    isComplete: true,
    status: 'READY',
    createdById: 'user-3',
    createdBy: getUserById('user-3'),
    createdAt: '2024-03-02T10:30:00Z',
    updatedAt: '2024-03-02T10:30:00Z',
  },
  {
    id: 'tc-3',
    applicationId: 'app-1',
    testRequestId: 'tr-2',
    requirementId: 'req-2',
    flowId: 'flow-3',
    title: 'تست فیلتر گزارش بر اساس تاریخ',
    scenario: 'کاربر گزارش تراکنش‌ها را با فیلتر تاریخ مشاهده می‌کند',
    preconditions: 'کاربر لاگین کرده باشد\nتراکنش‌های قبلی وجود داشته باشد',
    testData: 'تاریخ شروع: ابتدای ماه\nتاریخ پایان: امروز',
    steps: '۱. ورود به منوی گزارش‌ها\n۲. انتخاب فیلتر تاریخ\n۳. انتخاب بازه زمانی\n۴. مشاهده نتایج',
    expectedResult: 'فقط تراکنش‌های در بازه زمانی انتخاب شده نمایش داده شوند',
    testType: 'FUNCTIONAL',
    testDesignTechnique: 'EQUIVALENCE_PARTITIONING',
    priority: 'MEDIUM',
    riskLevel: 'LOW',
    qualityAttribute: 'FUNCTIONALITY',
    automationCandidate: true,
    regressionCandidate: false,
    isActive: true,
    isComplete: true,
    status: 'READY',
    createdById: 'user-3',
    createdBy: getUserById('user-3'),
    createdAt: '2024-03-03T09:00:00Z',
    updatedAt: '2024-03-03T09:00:00Z',
  },
];

// Test Runs
export const mockTestRuns: TestRun[] = [
  {
    id: 'run-1',
    testCaseId: 'tc-1',
    testCase: mockTestCases[0],
    testRequestId: 'tr-1',
    applicationId: 'app-1',
    version: '2.5.0',
    buildNumber: '1234',
    status: 'PASSED',
    actualResult: 'انتقال با موفقیت ثبت شد و در لیست زمان‌بندی‌ها نمایش داده شد',
    executedById: 'user-3',
    executedBy: getUserById('user-3'),
    executedAt: '2024-03-03T11:00:00Z',
    isFinalized: true,
    isLocked: false,
    createdAt: '2024-03-03T10:30:00Z',
    updatedAt: '2024-03-03T11:00:00Z',
  },
  {
    id: 'run-2',
    testCaseId: 'tc-2',
    testCase: mockTestCases[1],
    testRequestId: 'tr-1',
    applicationId: 'app-1',
    version: '2.5.0',
    buildNumber: '1234',
    status: 'FAILED',
    actualResult: 'پیام خطا نمایش داده نشد و انتقال انجام شد',
    executedById: 'user-3',
    executedBy: getUserById('user-3'),
    executedAt: '2024-03-03T11:30:00Z',
    isFinalized: true,
    isLocked: false,
    createdAt: '2024-03-03T11:00:00Z',
    updatedAt: '2024-03-03T11:30:00Z',
  },
  {
    id: 'run-3',
    testCaseId: 'tc-3',
    testCase: mockTestCases[2],
    testRequestId: 'tr-2',
    applicationId: 'app-1',
    version: '2.5.0',
    buildNumber: '1235',
    status: 'BLOCKED',
    actualResult: 'دسترسی به سرور گزارش‌گیری مقدور نبود',
    executedById: 'user-3',
    executedBy: getUserById('user-3'),
    executedAt: '2024-03-04T09:00:00Z',
    isFinalized: false,
    isLocked: false,
    createdAt: '2024-03-04T08:30:00Z',
    updatedAt: '2024-03-04T09:00:00Z',
  },
  {
    id: 'run-4',
    testCaseId: 'tc-1',
    testCase: mockTestCases[0],
    testRequestId: 'tr-1',
    applicationId: 'app-1',
    version: '2.5.0',
    buildNumber: '1234',
    status: 'PENDING',
    executedById: 'user-3',
    executedBy: getUserById('user-3'),
    isFinalized: false,
    isLocked: false,
    createdAt: '2024-03-05T10:00:00Z',
    updatedAt: '2024-03-05T10:00:00Z',
  },
];

// Bugs
export const mockBugs: Bug[] = [
  {
    id: 'bug-1',
    applicationId: 'app-1',
    testRunId: 'run-2',
    testRun: mockTestRuns[1],
    title: 'عدم نمایش پیام خطا برای موجودی ناکافی',
    description: 'هنگام انتقال مبلغی بیش از موجودی، پیام خطا نمایش داده نمی‌شود و تراکنش انجام می‌شود',
    stepsToReproduce: '۱. ورود با کاربر تست\n۲. رفتن به انتقال وجه\n۳. وارد کردن مبلغ ۱۰۰۰۰۰۰ (موجودی ۵۰۰۰۰۰)\n۴. تایید انتقال',
    expectedResult: 'نمایش پیام خطا: موجودی ناکافی',
    actualResult: 'تراکنش بدون خطا انجام شد',
    severity: 'CRITICAL',
    priority: 'CRITICAL',
    status: 'ASSIGNED',
    assigneeId: 'user-1',
    assignee: getUserById('user-1'),
    reportedById: 'user-3',
    reportedBy: getUserById('user-3'),
    createdAt: '2024-03-03T12:00:00Z',
    updatedAt: '2024-03-03T12:00:00Z',
  },
  {
    id: 'bug-2',
    applicationId: 'app-1',
    testRunId: 'run-2',
    testRun: mockTestRuns[1],
    title: 'عدم بررسی موجودی قبل از تایید',
    description: 'سیستم موجودی حساب را قبل از تایید نهایی بررسی نمی‌کند',
    stepsToReproduce: '۱. ورود به سیستم\n۲. انتقال وجه با مبلغ بالا\n۳. تایید',
    expectedResult: 'بررسی موجودی و نمایش خطا',
    actualResult: 'تراکنش تایید شد',
    severity: 'MAJOR',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    assigneeId: 'user-1',
    assignee: getUserById('user-1'),
    reportedById: 'user-3',
    reportedBy: getUserById('user-3'),
    fixNotes: 'در حال بررسی منطق اعتبارسنجی',
    createdAt: '2024-03-03T12:30:00Z',
    updatedAt: '2024-03-04T10:00:00Z',
  },
  {
    id: 'bug-3',
    applicationId: 'app-1',
    testRunId: 'run-1',
    testRun: mockTestRuns[0],
    title: 'تاخیر در نمایش انتقال در لیست',
    description: 'پس از ثبت انتقال، نمایش در لیست با تاخیر انجام می‌شود',
    stepsToReproduce: '۱. ثبت انتقال جدید\n۲. مشاهده لیست انتقال‌ها',
    expectedResult: 'نمایش فوری انتقال جدید',
    actualResult: 'نمایش با تاخیر ۵-۱۰ ثانیه',
    severity: 'MINOR',
    priority: 'LOW',
    status: 'FIXED',
    assigneeId: 'user-8',
    assignee: getUserById('user-8'),
    reportedById: 'user-3',
    reportedBy: getUserById('user-3'),
    fixedVersion: '2.5.1',
    fixNotes: 'مشکل کش رفع شد',
    createdAt: '2024-03-03T13:00:00Z',
    updatedAt: '2024-03-05T14:00:00Z',
  },
];

export const mockRetestTasks: RetestTask[] = [];

// Run Issues
export const mockRunIssues: RunIssue[] = [
  {
    id: 'ri-1',
    testRunId: 'run-3',
    testRun: mockTestRuns[2],
    applicationId: 'app-1',
    issueType: 'ENVIRONMENT',
    title: 'سرور گزارش‌گیری در دسترس نیست',
    description: 'سرور گزارش‌گیری staging از دسترس خارج شده و امکان تست وجود ندارد',
    status: 'OPEN',
    reportedById: 'user-3',
    reportedBy: getUserById('user-3'),
    createdAt: '2024-03-04T09:00:00Z',
    updatedAt: '2024-03-04T09:00:00Z',
  },
];

// Checklists
export const mockChecklists: Checklist[] = [
  {
    id: 'cl-1',
    applicationId: 'app-1',
    testRequestId: 'tr-3',
    type: 'SECURITY',
    status: 'IN_PROGRESS',
    items: [
      { id: 'cli-1', checklistId: 'cl-1', title: 'بررسی احراز هویت', description: 'تایید صحت مکانیزم احراز هویت', result: 'PASS', order: 1 },
      { id: 'cli-2', checklistId: 'cl-1', title: 'بررسی مجوزها', description: 'تایید صحت سیستم مجوزدهی', result: 'PASS', order: 2 },
      { id: 'cli-3', checklistId: 'cl-1', title: 'بررسی رمزنگاری', description: 'بررسی رمزنگاری داده‌ها', order: 3 },
      { id: 'cli-4', checklistId: 'cl-1', title: 'بررسی XSS', description: 'بررسی آسیب‌پذیری XSS', order: 4 },
      { id: 'cli-5', checklistId: 'cl-1', title: 'بررسی CSRF', description: 'بررسی آسیب‌پذیری CSRF', order: 5 },
    ],
    reviewedById: 'user-5',
    reviewedBy: getUserById('user-5'),
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-03-02T15:00:00Z',
  },
  {
    id: 'cl-2',
    applicationId: 'app-1',
    testRequestId: 'tr-3',
    type: 'PERFORMANCE',
    status: 'PENDING',
    items: [
      { id: 'cli-6', checklistId: 'cl-2', title: 'تست بارگذاری', description: 'تست با ۱۰۰۰ کاربر همزمان', order: 1 },
      { id: 'cli-7', checklistId: 'cl-2', title: 'تست زمان پاسخ', description: 'بررسی زمان پاسخ API', order: 2 },
      { id: 'cli-8', checklistId: 'cl-2', title: 'تست حافظه', description: 'بررسی مصرف حافظه', order: 3 },
    ],
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-03-01T10:00:00Z',
  },
];

// Playwright Runs
export const mockPlaywrightRuns: PlaywrightRun[] = [
  {
    id: 'pw-1',
    applicationId: 'app-1',
    testRequestId: 'tr-1',
    testFilePath: 'tests/transfer/scheduled-transfer.spec.ts',
    environment: 'staging',
    status: 'PASSED',
    startedAt: '2024-03-03T14:00:00Z',
    completedAt: '2024-03-03T14:05:00Z',
    duration: 300,
    totalTests: 10,
    passedTests: 10,
    failedTests: 0,
    skippedTests: 0,
    triggeredById: 'user-3',
    triggeredBy: getUserById('user-3'),
    createdAt: '2024-03-03T14:00:00Z',
    updatedAt: '2024-03-03T14:05:00Z',
  },
  {
    id: 'pw-2',
    applicationId: 'app-1',
    testRequestId: 'tr-2',
    testFilePath: 'tests/reports/financial-report.spec.ts',
    environment: 'staging',
    status: 'FAILED',
    startedAt: '2024-03-04T10:00:00Z',
    completedAt: '2024-03-04T10:03:00Z',
    duration: 180,
    totalTests: 8,
    passedTests: 5,
    failedTests: 3,
    skippedTests: 0,
    logs: 'Error: Element not found: #report-download-btn\nTimeout waiting for selector',
    triggeredById: 'user-3',
    triggeredBy: getUserById('user-3'),
    createdAt: '2024-03-04T10:00:00Z',
    updatedAt: '2024-03-04T10:03:00Z',
  },
  {
    id: 'pw-3',
    applicationId: 'app-1',
    testFilePath: 'tests/auth/two-factor.spec.ts',
    environment: 'staging',
    status: 'RUNNING',
    startedAt: '2024-03-05T11:00:00Z',
    totalTests: 15,
    triggeredById: 'user-2',
    triggeredBy: getUserById('user-2'),
    createdAt: '2024-03-05T11:00:00Z',
    updatedAt: '2024-03-05T11:00:00Z',
  },
];

// Release Publishes
export const mockReleasePublishes: ReleasePublish[] = [
  {
    id: 'rp-1',
    applicationId: 'app-1',
    version: '2.4.5',
    buildNumber: '1200',
    status: 'PUBLISHED',
    primaryTestRequestId: 'tr-old-1',
    relatedRequestIds: ['tr-old-2'],
    isEmergency: false,
    qaQualityStatus: 'READY',
    qaQualityNotes: 'تمام تست‌ها با موفقیت اجرا شدند',
    qaReviewedById: 'user-2',
    qaReviewedBy: getUserById('user-2'),
    qaReviewedAt: '2024-02-25T14:00:00Z',
    decision: 'APPROVED',
    decisionReason: 'آماده برای انتشار',
    decisionById: 'user-6',
    decisionBy: getUserById('user-6'),
    decisionAt: '2024-02-25T15:00:00Z',
    testRequestIds: ['tr-old-1', 'tr-old-2'],
    snapshot: {
      totalTestCases: 50,
      passedTestRuns: 48,
      failedTestRuns: 2,
      blockedTestRuns: 0,
      totalBugs: 5,
      criticalBugs: 0,
      majorBugs: 0,
      openBugs: 0,
      closedBugs: 5,
      securityChecklistResult: 'PASS',
      performanceChecklistResult: 'PASS',
      playwrightPassRate: 96,
      capturedAt: '2024-02-25T14:00:00Z',
    },
    createdById: 'user-2',
    createdBy: getUserById('user-2'),
    createdAt: '2024-02-25T10:00:00Z',
    updatedAt: '2024-02-25T15:00:00Z',
    publishedAt: '2024-02-25T16:00:00Z',
  },
  {
    id: 'rp-2',
    applicationId: 'app-1',
    version: '2.5.0',
    buildNumber: '1234',
    status: 'QA_REVIEW',
    primaryTestRequestId: 'tr-1',
    relatedRequestIds: ['tr-2'],
    isEmergency: false,
    testRequestIds: ['tr-1', 'tr-2'],
    createdById: 'user-2',
    createdBy: getUserById('user-2'),
    createdAt: '2024-03-05T09:00:00Z',
    updatedAt: '2024-03-05T09:00:00Z',
  },
  {
    id: 'rp-3',
    applicationId: 'app-1',
    version: '2.4.6',
    buildNumber: '1210',
    status: 'EMERGENCY',
    primaryTestRequestId: 'tr-3',
    relatedRequestIds: [],
    isEmergency: true,
    emergencyReason: 'رفع اشکال امنیتی بحرانی در احراز هویت',
    riskDescription: 'انتشار بدون تست کامل رگرسیون',
    riskAccepted: true,
    qaQualityStatus: 'CONDITIONAL',
    qaQualityNotes: 'فقط تست‌های امنیتی اجرا شده',
    qaReviewedById: 'user-2',
    qaReviewedBy: getUserById('user-2'),
    qaReviewedAt: '2024-02-20T10:00:00Z',
    decision: 'APPROVED',
    decisionReason: 'انتشار اضطراری با پذیرش ریسک',
    decisionById: 'user-6',
    decisionBy: getUserById('user-6'),
    decisionAt: '2024-02-20T10:30:00Z',
    testRequestIds: [],
    snapshot: {
      totalTestCases: 10,
      passedTestRuns: 10,
      failedTestRuns: 0,
      blockedTestRuns: 0,
      totalBugs: 1,
      criticalBugs: 1,
      majorBugs: 0,
      openBugs: 0,
      closedBugs: 1,
      securityChecklistResult: 'PASS',
      capturedAt: '2024-02-20T10:00:00Z',
    },
    createdById: 'user-2',
    createdBy: getUserById('user-2'),
    createdAt: '2024-02-20T09:00:00Z',
    updatedAt: '2024-02-20T11:00:00Z',
    publishedAt: '2024-02-20T11:00:00Z',
  },
];

// Audit Logs
export const mockAuditLogs: AuditLog[] = [
  {
    id: 'audit-1',
    userId: 'user-1',
    user: getUserById('user-1'),
    applicationId: 'app-1',
    application: getApplicationById('app-1'),
    entityType: 'TEST_REQUEST',
    entityId: 'tr-1',
    action: 'CREATE',
    newValue: JSON.stringify({ title: 'تست ویژگی انتقال وجه جدید' }),
    createdAt: '2024-03-01T10:00:00Z',
  },
  {
    id: 'audit-2',
    userId: 'user-1',
    user: getUserById('user-1'),
    applicationId: 'app-1',
    application: getApplicationById('app-1'),
    entityType: 'TEST_REQUEST',
    entityId: 'tr-1',
    action: 'SUBMIT',
    previousValue: JSON.stringify({ status: 'DRAFT' }),
    newValue: JSON.stringify({ status: 'SUBMITTED' }),
    createdAt: '2024-03-01T10:30:00Z',
  },
  {
    id: 'audit-3',
    userId: 'user-2',
    user: getUserById('user-2'),
    applicationId: 'app-1',
    application: getApplicationById('app-1'),
    entityType: 'TEST_REQUEST',
    entityId: 'tr-2',
    action: 'ASSIGN',
    newValue: JSON.stringify({ assigneeId: 'user-3' }),
    createdAt: '2024-03-02T11:00:00Z',
  },
  {
    id: 'audit-4',
    userId: 'user-3',
    user: getUserById('user-3'),
    applicationId: 'app-1',
    application: getApplicationById('app-1'),
    entityType: 'BUG',
    entityId: 'bug-1',
    action: 'CREATE',
    newValue: JSON.stringify({ title: 'عدم نمایش پیام خطا برای موجودی ناکافی', severity: 'CRITICAL' }),
    createdAt: '2024-03-03T12:00:00Z',
  },
  {
    id: 'audit-5',
    userId: 'user-6',
    user: getUserById('user-6'),
    applicationId: 'app-1',
    application: getApplicationById('app-1'),
    entityType: 'RELEASE_PUBLISH',
    entityId: 'rp-3',
    action: 'EMERGENCY_PUBLISH',
    newValue: JSON.stringify({ version: '2.4.6', emergencyReason: 'رفع اشکال امنیتی بحرانی' }),
    createdAt: '2024-02-20T11:00:00Z',
  },
];

// Comments
export const mockComments: Comment[] = [
  {
    id: 'comment-1',
    entityType: 'BUG',
    entityId: 'bug-1',
    content: 'این مشکل فوری است و باید در اسرع وقت رفع شود',
    authorId: 'user-2',
    author: getUserById('user-2'),
    createdAt: '2024-03-03T12:30:00Z',
    updatedAt: '2024-03-03T12:30:00Z',
  },
  {
    id: 'comment-2',
    entityType: 'BUG',
    entityId: 'bug-1',
    content: 'در حال بررسی هستم، احتمالا مربوط به تغییرات اخیر در سرویس موجودی است',
    authorId: 'user-1',
    author: getUserById('user-1'),
    createdAt: '2024-03-03T13:00:00Z',
    updatedAt: '2024-03-03T13:00:00Z',
  },
  {
    id: 'comment-3',
    entityType: 'RELEASE_PUBLISH',
    entityId: 'rp-2',
    content: 'باگ‌های بحرانی باید قبل از انتشار رفع شوند',
    authorId: 'user-7',
    author: getUserById('user-7'),
    createdAt: '2024-03-05T10:00:00Z',
    updatedAt: '2024-03-05T10:00:00Z',
  },
];

// Notifications
export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-2',
    title: 'درخواست تست جدید',
    message: 'درخواست تست "تست ویژگی انتقال وجه جدید" ارسال شد',
    type: 'INFO',
    entityType: 'TEST_REQUEST',
    entityId: 'tr-1',
    isRead: false,
    createdAt: '2024-03-01T10:30:00Z',
  },
  {
    id: 'notif-2',
    userId: 'user-1',
    title: 'باگ جدید تخصیص یافت',
    message: 'باگ "عدم نمایش پیام خطا برای موجودی ناکافی" به شما تخصیص یافت',
    type: 'WARNING',
    entityType: 'BUG',
    entityId: 'bug-1',
    isRead: false,
    createdAt: '2024-03-03T12:00:00Z',
  },
  {
    id: 'notif-3',
    userId: 'user-3',
    title: 'درخواست تست ارجاع شد',
    message: 'درخواست تست "تست ماژول گزارش‌گیری مالی" به شما ارجاع شد',
    type: 'INFO',
    entityType: 'TEST_REQUEST',
    entityId: 'tr-2',
    isRead: true,
    createdAt: '2024-03-02T11:00:00Z',
  },
  {
    id: 'notif-4',
    userId: 'user-6',
    title: 'انتشار آماده تصمیم‌گیری',
    message: 'نسخه ۲.۵.۰ آماده تصمیم‌گیری برای انتشار است',
    type: 'INFO',
    entityType: 'RELEASE_PUBLISH',
    entityId: 'rp-2',
    isRead: false,
    createdAt: '2024-03-05T09:00:00Z',
  },
  {
    id: 'notif-5',
    userId: 'user-5',
    title: 'چک‌لیست امنیتی جدید',
    message: 'چک‌لیست امنیتی برای درخواست تست "تست امنیتی ورود دو مرحله‌ای" ایجاد شد',
    type: 'INFO',
    entityType: 'CHECKLIST',
    entityId: 'cl-1',
    isRead: true,
    createdAt: '2024-03-01T10:00:00Z',
  },
];

// Attachments
export const mockAttachments: Attachment[] = [
  {
    id: 'att-1',
    entityType: 'TEST_RUN',
    entityId: 'run-2',
    type: 'SCREENSHOT',
    fileName: 'error-screenshot.png',
    fileSize: 256000,
    mimeType: 'image/png',
    storagePath: '/attachments/run-2/error-screenshot.png',
    status: 'VALID',
    uploadedById: 'user-3',
    uploadedBy: getUserById('user-3'),
    createdAt: '2024-03-03T11:30:00Z',
    updatedAt: '2024-03-03T11:30:00Z',
  },
  {
    id: 'att-2',
    entityType: 'BUG',
    entityId: 'bug-1',
    type: 'LOG',
    fileName: 'console-log.txt',
    fileSize: 12000,
    mimeType: 'text/plain',
    storagePath: '/attachments/bug-1/console-log.txt',
    status: 'VALID',
    uploadedById: 'user-3',
    uploadedBy: getUserById('user-3'),
    createdAt: '2024-03-03T12:00:00Z',
    updatedAt: '2024-03-03T12:00:00Z',
  },
  {
    id: 'att-3',
    entityType: 'PLAYWRIGHT_RUN',
    entityId: 'pw-1',
    type: 'REPORT',
    fileName: 'playwright-report.html',
    fileSize: 1024000,
    mimeType: 'text/html',
    storagePath: '/attachments/pw-1/playwright-report.html',
    status: 'VALID',
    uploadedById: 'user-3',
    uploadedBy: getUserById('user-3'),
    createdAt: '2024-03-03T14:05:00Z',
    updatedAt: '2024-03-03T14:05:00Z',
  },
];

// Helper to generate IDs
export const generateId = (): string => uuidv4();

// Helper to get current timestamp
export const getCurrentTimestamp = (): string => new Date().toISOString();
