export function scenariosFor(config, profile) {
  const loadStages = [
    { duration: config.rampDuration, target: config.rate },
    { duration: config.duration, target: config.rate },
    { duration: config.rampDuration, target: 0 },
  ];
  const scenarios = {
    smoke: {
      executor: 'constant-vus',
      vus: Math.min(config.vus || 1, 2),
      duration: config.duration || '1m',
      exec: 'apiConsoleWorkload',
      tags: { profile: 'smoke' },
    },
    baseline: {
      executor: 'shared-iterations',
      vus: 1,
      iterations: Math.max(8, config.datasetSize),
      maxDuration: config.duration || '5m',
      exec: 'baselineWorkload',
      tags: { profile: 'baseline' },
    },
    load: {
      executor: 'ramping-arrival-rate',
      startRate: 1,
      timeUnit: '1s',
      preAllocatedVUs: Math.max(4, config.vus),
      maxVUs: config.maxVus,
      stages: loadStages,
      exec: 'apiConsoleWorkload',
      tags: { profile: 'load' },
    },
    stress: {
      executor: 'ramping-arrival-rate',
      startRate: 1,
      timeUnit: '1s',
      preAllocatedVUs: Math.max(8, config.vus),
      maxVUs: Math.max(config.maxVus, config.peakRate * 2),
      stages: [
        { duration: config.rampDuration, target: config.rate },
        { duration: config.rampDuration, target: config.peakRate },
        { duration: config.duration, target: config.peakRate },
        { duration: config.rampDuration, target: 0 },
      ],
      exec: 'apiConsoleWorkload',
      tags: { profile: 'stress' },
    },
    spike: {
      executor: 'ramping-arrival-rate',
      startRate: 1,
      timeUnit: '1s',
      preAllocatedVUs: Math.max(8, config.vus),
      maxVUs: Math.max(config.maxVus, config.peakRate * 2),
      stages: [
        { duration: config.rampDuration, target: 1 },
        { duration: config.rampDuration, target: config.peakRate },
        { duration: config.duration, target: config.peakRate },
        { duration: config.rampDuration, target: 1 },
        { duration: config.duration, target: 1 },
      ],
      exec: 'apiConsoleWorkload',
      tags: { profile: 'spike' },
    },
    soak: {
      executor: 'constant-arrival-rate',
      rate: config.rate,
      timeUnit: '1s',
      duration: config.duration || '10m',
      preAllocatedVUs: Math.max(4, config.vus),
      maxVUs: config.maxVus,
      exec: 'apiConsoleWorkload',
      tags: { profile: 'soak' },
    },
    scalability: {
      executor: 'ramping-arrival-rate',
      startRate: config.rate,
      timeUnit: '1s',
      preAllocatedVUs: Math.max(8, config.vus),
      maxVUs: Math.max(config.maxVus, config.rate * 8),
      stages: [
        { duration: config.rampDuration, target: config.rate },
        { duration: config.duration, target: config.rate },
        { duration: config.rampDuration, target: config.rate * 2 },
        { duration: config.duration, target: config.rate * 2 },
        { duration: config.rampDuration, target: config.rate * 3 },
        { duration: config.duration, target: config.rate * 3 },
        { duration: config.rampDuration, target: config.rate * 5 },
        { duration: config.duration, target: config.rate * 5 },
        { duration: config.rampDuration, target: 0 },
      ],
      exec: 'apiConsoleWorkload',
      tags: { profile: 'scalability' },
    },
    recovery: {
      executor: 'ramping-arrival-rate',
      startRate: 1,
      timeUnit: '1s',
      preAllocatedVUs: Math.max(8, config.vus),
      maxVUs: config.maxVus,
      stages: [
        { duration: config.rampDuration, target: config.rate },
        { duration: config.duration, target: config.peakRate },
        { duration: config.duration, target: config.rate },
        { duration: config.rampDuration, target: 0 },
      ],
      exec: 'recoveryWorkload',
      tags: { profile: 'recovery' },
    },
    breakpoint: {
      executor: 'ramping-arrival-rate',
      startRate: config.rate,
      timeUnit: '1s',
      preAllocatedVUs: Math.max(10, config.vus),
      maxVUs: Math.max(config.maxVus, config.peakRate * 4),
      stages: [
        { duration: config.rampDuration, target: config.rate },
        { duration: config.rampDuration, target: config.rate * 2 },
        { duration: config.rampDuration, target: config.rate * 4 },
        { duration: config.rampDuration, target: config.rate * 8 },
        { duration: config.duration, target: config.rate * 8 },
      ],
      exec: 'apiConsoleWorkload',
      tags: { profile: 'breakpoint' },
    },
  };
  return { [profile]: scenarios[profile] };
}
